version: 2.1

jobs: 
    react-test:
      docker:
        - image: node:latest-browsers
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
      steps:
        - checkout
        - run:
            name: Install react Dependencies
            command: cd ~/crew_manual/Frontend && npm install --force
        - run: 
            name: Run Frontend Testcases
            command: cd ~/crew_manual/Frontend && npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
    
    build_and_push:
      docker:
        - image: node:latest-browsers
      steps:
        - checkout
        - setup_remote_docker:
            version: 19.03.13
        - run:
            name: Build Docker Image
            command: cd ~/crew_manual && docker build -t $alar12/donationProject:v1 .
        - run:
            name: Authenticate with Docker Hub
            command: cd ~/crew_manual && echo "$Aa12345*" | docker login --username $alar12 --password-Aa12345*
        - run:
            name: Push Docker Image to Docker Hub
            command: cd ~/crew_manual && docker push $alar12/donationProject:v1

workflows:
    Testcases:
      jobs:
        - node/run:
            pkg-manager: npm 
            resource_class: large 
            app-dir: ~/crew_manual/Backend 
            npm-run: test

        - react-test
    
    build_and_deploy:
      jobs:
        - build_and_push